### PR TITLE
Move benchmark

### PR DESCRIPTION
**Pull request by hn8**
https://github.com/go-logr/zerologr/issues/9

### CODE REVIEW

**Review by pohly — COMMENTED** [review]
Where is this going to be moved to?

**Comment by thockin** [comment]
Should we make a new `go-logr/benchmark` repo?

**Comment by hn8** [comment]
Moved to https://github.com/go-logr/benchmark

**Comment by hn8** [comment]
@thockin @pohly Moved to https://github.com/go-logr/benchmark

**Pull request merged**
