### PR TITLE
Fixed Enabled() for lazy evaluation and supporting >2 V-level

### PR DESCRIPTION
**Pull request by hn8**
- Support logr.Enabled() usage for lazy argument preparation.
- Add SetMaxV function to change max V-level without knowledge of Zerolog's internal.
- Add support and warning for >2 V-level usage.

Close PR https://github.com/go-logr/zerologr/pull/22, https://github.com/go-logr/zerologr/pull/23, https://github.com/go-logr/zerologr/pull/24. Issue https://github.com/go-logr/zerologr/issues/20

### CODE REVIEW

**Comment by thockin** [comment]
So you don't want to document how to make higher V levels work at all?  This puts zerologr into the "not interesting" category, IMO.

**Comment by hn8** [comment]
@thockin @pohly As I mentioned in the other thread, zapr is definitely much better choice than zerologr if higher than 2 verbosity (TraceLevel) is needed. Here are the reasons:
1. To use an undocumented zerolog levels, user need to figure out which zerolog levels to use by digging out zerolog source code. And zerolog's level value is in opposite direction of logr verbosity. It is easy to use zerolog.DebugLevel or zerolog.TraceLevel. It is confusing to set zerolog level to -5 to allow logr.V(6).
2. In zerolog, there are two level checks: one is global atomic variable, the other is stored in zerolog.Logger passing in zerologr.New(). By default, zerolog.Logger is set to TraceLevel, so most zerolog users only need to adjust global level, rarely need to adjust the level of local logger. To use undocumented zerolog levels, users will need to remember to set level in both zerolog.Logger and globally. And once zerologr.New is called, users have no easy way to adjust level of underlying zerolog.Logger locally.
3. Undocumented level can not support at least two zerolog features: Hooks and Sampling. And probably will never can since those two are implemented as struct. 
4. By default, zerologr outputs both zerolog and logr label { "level": "trace", "v": 2 }, and users can disable either if needed. Otherwises, undocumented zerolog level would have output like { "level": "-2", "v": 3 } which is quite confusing.

logr is greate for Go library users since any logging libraries (ofthen the same one used in application code) can swap in without hardcoded. If users choose to use zerolog for application code, it is likely they know they can only use highest verbosity up to TraceLevel without reading zerolog's source code and can use all features like Sampling. On the other hand, if users prefer to use logr directly in application code, they are more freedom to choose from logr implementation.

zerologr is the minimal glue between logr and zerolog and is limited by both. For example, logr does not support zerolog's WarnLevel/FatalLevel/PanicLevel. And zerolog does not support higher than logr.V(2) by default. Now, with this PR, it is possible for zerologr to support higher than logr.V(2) by setting EnforceLevelCheck=true but it breaks zerolog if zerolog's Hooks/Sampling is used. 

IMHO, it is better to keep zerologr less interesting and also less confusing by default. If users want to hack zerolog's undocumented level, there is an option to do so, but it is not supported by us (zerologr maintainer.

**Comment by hn8** [comment]
@thockin @pohly Also, maybe the root cause of this PR is where Enabled() should be called. I can move the dicussion to logr instead. About this line https://github.com/go-logr/logr/blob/master/logr.go#L274

Among all listed logr implementation, some (funcr, testr, glogr, klogr, ktesting, stdr, genericr, logfmtr) rely on logr.Enabled() check and the other (zapr, zerologr, logrusr, gokitlogr, bufrlogr) also check again either in LogSink.Info() or underlying logging library calls. Since some established logging library already check level internally, it might be nice to move Enabled() call from Logr.Info() to LogSink.Info() to prevent the redundant Enabled() call in the logging hotpath, but that ship has sailed.

**Comment by pohly** [comment]
> it might be nice to move Enabled() call from Logr.Info() to LogSink.Info() to prevent the redundant Enabled() call in the logging hotpath, but that ship has sailed.

The reason for it being in `Logger.Info` is that the check is visible to the compiler. The hope was (and still is) that in the common case of not emitting a debug message, the compiler will generate optimized code where the expensive work of preparing parameters for the `Info` call can be skipped - see https://github.com/golang/go/issues/53465#issuecomment-1322594798

**Comment by hn8** [comment]
Understood the point of logr.Enabled() for lazy argument preparation. But it means that level checks will run two times for most logr implementation, three times for zerologr, may four times for zapr in logr.Info() call. Don't have a better solution though.

**Comment by hn8** [comment]
@thockin @pohly Thanks for the feedback. I added SetMaxV function to reduce level-mapping confusing. And hopefully all related issues for non-conforming Enabled() and high verbosity are resolved.

**Review by tonglil — APPROVED** [review]
Thank you for taking additional verbosity into consideration, this LGTM!

**Comment by thockin** [comment]
LGTM

**Pull request merged**
